// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import ()

type Album struct {
	ID        int64   `json:"id"`
	Title     string  `json:"title"`
	Year      int64   `json:"year"`
	Genre     string  `json:"genre"`
	CoverPath *string `json:"coverPath"`
}

type AlbumArtist struct {
	AlbumID  int64 `json:"albumId"`
	ArtistID int64 `json:"artistId"`
}

type Artist struct {
	ID          int64   `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

type Stream struct {
	ID        int64  `json:"id"`
	Bitrate   int64  `json:"bitrate"`
	Equalizer string `json:"equalizer"`
	Path      string `json:"path"`
	TrackID   int64  `json:"trackId"`
}

type Track struct {
	ID        int64   `json:"id"`
	Title     string  `json:"title"`
	Position  int64   `json:"position"`
	Length    int64   `json:"length"`
	Bitrate   int64   `json:"bitrate"`
	AlbumID   int64   `json:"albumId"`
	Format    string  `json:"format"`
	Path      string  `json:"path"`
	AudioPath string  `json:"audioPath"`
	CoverPath *string `json:"coverPath"`
}

type TrackArtist struct {
	TrackID  int64 `json:"trackId"`
	ArtistID int64 `json:"artistId"`
}
